version: "2"
services:
  mongodb_dev:
    restart: always
    container_name: local-mongo
    image: mongo:4.2.7-bionic
    networks:
      - local-mongo-net
    environment:
      - "MONGO_INITDB_DATABASE=local-mongo"
    volumes:
      - local-mongo-volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: --bind_ip_all --replSet rs0
    ports:
      - "27017:27017"
networks:
  local-mongo-net:
    driver: bridge

volumes:
  local-mongo-volume:
    driver: local
